name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ninie-io" #Must be unique in Heroku
          heroku_email: "mottet.lionel@gmail.com"
          buildpack: "https://github.com/chibat/heroku-buildpack-deno.git"
          dontuseforce: true
        env:
          HD_DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
          HD_DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
